FROM nginx:1.18-alpine

# Add group & user www-data
RUN set -x ; \
  addgroup -g 82 -S www-data ; \
  adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

COPY nginx/default.conf /etc/nginx/conf.d
COPY nginx/nginx.conf /etc/nginx/nginx.conf

ARG hostname

RUN echo "upstream php-upstream { server ${hostname}:9000; }" > /etc/nginx/conf.d/upstream.conf

EXPOSE 80
